Feature/jc19 332 table pagination sorted
saritasa-nest/camp-js-2022-dmitry-maslov pull request #1
Opened 2022-07-12 10:22 UTC by dmitriqm

2022-07-12 14:51 UTC, panov-aleksey-saritasa commented
@dmitriqm please, stick to [our convention](https://wiki.saritasa.rocks/frontend/tools/git#commit-messages) for naming commits

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa requested changes

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  public mount(): void {
The name isn't clear, please rename it.

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableElements.ts
> +   * Creates a root html element.
Please, fix docs and name of function.

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +        switch (header.status) {
It is not good practice to use `switch`, try to avoid it, you can find a lot of information about it, [for example](https://www.youtube.com/watch?v=7T051-eeacQ)

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +interface Header {
Add docs please

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/paginationPanel.ts
> +    const lastPageNumber = Math.floor(count / limit + (count % limit > 0 ? 1 : 0));
I think you can use [Math.ceil](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil) to avoid extra calculations.

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/paginationPanel.ts
> +        endIterNumber = lastPageNumber - 1;
It is not clear what magic numbers are 2, 3, 7 ?

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/paginationPanel.ts
> +    const lastPageNumber = Math.floor(count / limit + (count % limit > 0 ? 1 : 0));
It is the same code as above, try to avoid copy-past

2022-07-13 04:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/services/anime.service.ts
> +export interface GetPaginatedListAnimeListResponse {
Fix naming please, word get isn't need in interface name

2022-07-13 05:24 UTC, golovachev-yaroslav requested changes

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +
Please remove emty rows.

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +
And reduce description`/** Pagination params. */`

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/src/components/AnimeTableComponents/animeTableElement.ts
> +  const $image = document.createElement('img');
Why do you use `$` for consts?

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +          alt=""
It would be better to add more clear name for alt, not empty string.

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +      <!-- Logo -->
I think this is redundant description, please remove.

2022-07-13 05:24 UTC, golovachev-yaroslav commented on apps/vanilla/tailwind.config.js
> +// apps/app1/tailwind.config.js
Not obvious why it's need, maybe remove?

2022-07-13 05:33 UTC, dmitriqm commented on apps/vanilla/src/components/AnimeTableComponents/animeTableElement.ts
> +  const $image = document.createElement('img');
I mark treehouse elements with $ symbol. But already deleted them.

2022-07-13 06:39 UTC, dmitriqm commented on apps/vanilla/src/components/AnimeTableComponents/paginationPanel.ts
> +    const lastPageNumber = Math.floor(count / limit + (count % limit > 0 ? 1 : 0));
Really! Thank you!

2022-07-13 06:40 UTC, dmitriqm commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +        offset: this.state.paginationParams.offset,
Really! Thank you!

2022-07-13 10:53 UTC, dmitriqm commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +        switch (header.status) {
Should there be something like this?
`
      const updateByStatusMethod = {
        [SortStatus.Not]: (): void => {
          this.updateMethod(order);
          header.status = SortStatus.Sort;
        },
        [SortStatus.Sort]: (): void => {
          this.updateMethod(reverseOrder);
          header.status = SortStatus.Reverse;
        },
        [SortStatus.Reverse]: (): void => {
          this.updateMethod(AnimeNotOrder.NotOrder);
          header.status = SortStatus.Not;
        },
      };

      updateByStatusMethod[status]();
`

2022-07-14 03:37 UTC, panov-aleksey-saritasa requested changes

2022-07-14 03:37 UTC, panov-aleksey-saritasa commented on libs/core/models/listAnime.ts
> +export class ListAnime extends Immerable {
Tbh, `ListAnime` is a confusing name Why not just name it `Anime`?
If it's some short version of `Anime` model, consider checking out this comment: https://github.com/saritasa-nest/camp-js-2022-andrey-alekseev/pull/1#discussion_r912565802 for details

2022-07-14 03:37 UTC, panov-aleksey-saritasa commented on libs/core/enums/anime/broadcastDay.enum.ts
> +/**
There is no need to add `.enum` to file names

2022-07-14 03:37 UTC, panov-aleksey-saritasa commented on libs/core/enums/anime/ordering.enum.ts
> +  ReversedTitleJpn = '-title_jpn',
Consider not mixing up fields by which sort is happening and sort direction. What I see right now is clear DRY violation 🙃

2022-07-14 03:37 UTC, panov-aleksey-saritasa commented on libs/core/enums/anime/ordering.enum.ts
> +
Be consistent, please, for other enums you are not separating values with blank lines

2022-07-14 03:37 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +        status: SortStatus.Not,
How about reducing it to just `order` and `status`? To improve readability you could even rename it to `sortField` and `sortDirection`

2022-07-14 07:06 UTC, elena-dragunova requested changes

2022-07-16 21:54 UTC, timofei-maximov-saritasa requested changes

2022-07-16 21:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> + */
Please fix docs and remove empty `@returns`

2022-07-16 21:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/anime.service.ts
> +  ordering: AnimeOrders;
Missing readonly

2022-07-16 21:54 UTC, timofei-maximov-saritasa commented on libs/core/models/pagination.ts
> +  public readonly results: T[];
Missing readonly for array
`public readonly results: readonly T[]`

2022-07-16 21:54 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly status: AnimeStatus;
You violated abstraction. You use `AnimeType` in your dto but `AnimeType` is a part of your domain. Consider using `AnimeTypeDto` for your `AnimeDto`.

2022-07-17 18:13 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +  updateMethod(order: AnimeOrders): void;
don't forget to add readonly.

2022-07-17 18:13 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/paginationPanel.ts
> +      next: this.createButton('>>'),
I think should move '>>' into constant.

2022-07-18 06:12 UTC, dmitriqm commented on libs/core/enums/anime/ordering.enum.ts
> +}
Do you mean it's better to just make it a variable and not an enum?
`export const AnimeNotOrder = ''`

2022-07-19 04:23 UTC, dmitriqm commented on apps/vanilla/src/pages/index.html
> +      </nav>
it is formatted with prettier😅

2022-07-20 04:02 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-20 04:02 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/components/paginationPanel.ts
> +    return itemList;
```suggestion
    return [
      PaginationElements.PreviousButton,
      ...startPages,
      ...second,
      ...this.range(siblingsStart, siblingsEnd),
      ...penult,
      ...endPages,
      PaginationElements.NextButton,
    ];
```

2022-07-20 04:19 UTC, golovachev-yaroslav approved these changes

2022-07-20 07:24 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-20 07:24 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  order: SortParams;
Let's rename it, `sort` instead of `order`

2022-07-20 07:24 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/components/AnimeTableComponents/animeTableHeader.ts
> +}
Move it in the start of the file.

2022-07-20 09:15 UTC, elena-dragunova approved these changes

2022-07-20 10:45 UTC, danilkukryakov requested changes

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  readonly count: number;
Usually we call such field `total`

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +    elements: [],
Are these params default? Maybe we can move them to a constant.

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  }
Maybe use TypeScript constructor [parameter property](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties).
Also the following sections from our wiki might be useful: [1](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-ordered-params-in-constructorsfunctions), [2](
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#parameter-property-comments).

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +    };
I'm a bit confused why we update the state manually and not through `setState` method like we do in `updateOrderState` and `updatePaginationState` methods?
Let's be consistent with state update approach and use single pattern everywhere.

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +    const root = document.querySelector(this.selector);
I'm can't get the idea why we need to initialise root element inside `render` method. Is it possible to select element from the DOM inside `constructor`?
As far as I can see you select the element from `index.html` by id (which is `table-root`). I guess, it will work the same way if we initialise root element inside the `constructor`.

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +   */
Please, adjust JSDoc comment formatting. Check this [section](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#place-docstring-parts-consistently) from our wiki.

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  }
I suppose, `setState` is a bad naming in this case because you don't just update the state. You have two actions here: state update + data fetch (and component refresh, I guess).
In my opinion, `setState` method should only update the state without any unexpected side effects.
In your particular case you can make `setState` method which accept something like `Partial<AnimeTableState>` and updates the component's state under the hood.

Otherwise, if you want to make something like React `setState` which do the folowing:
> schedules an update to a component’s state object. When state changes, the component responds by re-rendering.

Then only perform the component **re-rendering** and remove data fetching. Besides, adjust JSDoc because it's a bit misleading. `setState` won't refresh the whole page but rather the component itself.

2022-07-20 10:45 UTC, danilkukryakov commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  private tableElements = new TableElements();
Is it possible to make this field `readonly`. As I can see you don't reassign this property.

2022-07-20 16:39 UTC, pavelzadorin-saritasa requested changes

2022-07-22 13:19 UTC, dmitriqm commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  readonly count: number;
Discussed live. This field is configured like this on the backend, and it can be called like this

2022-08-05 06:50 UTC, chernodub requested changes
@dmitriqm 
1. Please make sure you never merge two features in a single PR. I see many parts of `vanilla` app are highlighted, this is very hard to review.
2. I don't see the pagination handling in Angular, even though the name of the PR makes me think that is what implemented

2022-08-05 06:50 UTC, chernodub commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +      <img class="anime-image" [src]="anime.image" alt="" />
Please specify alt for this image. Check out the helper that helps you understand whether alt is needed https://www.w3.org/WAI/tutorials/images/decision-tree/

2022-08-05 06:50 UTC, chernodub commented on apps/vanilla/src/components/AnimeTableComponents/animeTable.ts
> +  readonly order: SortParams;
Seems like the comment above was not resolved. Please revise our [CR conventions](https://wiki.saritasa.rocks/general/git#code-review:~:text=If%20you%20received%20a%20comment%20with%20which%20you%20do%20not%20agree%2C%20you%20must%20not%20resolve%20it%20silently.%20Answer%20it%2C%20and%20make%20sure%20the%20person%20who%20left%20the%20comment%20agreed%20with%20you%20(or%20vice%2Dversa).%20Only%20then%20a%20comment%20may%20be%20considered%20as%20resolved)

2022-08-29 07:57 UTC, closed without merging