Add angular table feature #JC19-398
saritasa-nest/camp-js-2022-dmitry-maslov pull request #4
Opened 2022-07-22 07:57 UTC by dmitriqm

2022-07-22 08:32 UTC, karbik-creator commented on apps/angular/src/core/services/anime.service.ts
> +          return animeList;
You don't need to create a array. I think you can rewrite it.
`map(animeDtoArray => animeDtoArray.map(animeDto => AnimeMapper.fromDto(animeDto)))`

2022-07-22 09:01 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-22 09:01 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-22 09:34 UTC, dmitriqm commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +import { AnimeService } from './../../../../core/services/anime.service';
@js-camp folder is not angular folder

2022-07-22 10:18 UTC, dmitriqm commented on apps/angular/src/environments/environment.ts
> +  apiUrl: 'https://api.camp-js.saritasa.rocks/api/v1/',
Discussed in slack

2022-07-22 10:18 UTC, dmitriqm commented on apps/angular/src/app/features/anime/anime.component.ts
> +export class AnimeComponent {
Discussed in slack

2022-07-22 10:19 UTC, dmitriqm commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +import { AnimeService } from './../../../../core/services/anime.service';
Discussed in slack

2022-07-22 11:03 UTC, dmitriqm commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +import { AnimeService } from './../../../../core/services/anime.service';
eslint swears on all paths except relative ones

2022-07-22 12:08 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/app.component.css
> +}
Move out this to `theme/styles`.
Btw, you have libs/theme/src/index.css for such global styles

2022-07-22 12:08 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.css
> +}
Prefer using css classes instead

2022-07-22 12:08 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/interceptors/api-key-interceptor.ts
> +   */
```suggestion
  /** @inheritdoc */
```

2022-07-22 12:08 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/app.component.css
> +}
We do not use `:host` for direct stylying, we use it for [styling via custom properties](https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#custom-properties-for-styling-components)
To keep it short and simple, think about `:host` as of interface between parent and child component. With this interface a parent component could change custom properties declared in the `:host` section of child component

2022-07-23 14:12 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +        map(animeDtoArray => animeDtoArray.map(animeDto => AnimeMapper.fromDto(animeDto))),
Why don't you pass response.results to mapper?

2022-07-23 14:12 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  ];
Missing readonly. Also, there is no need to to add type annotation, typescript can handle it, but if you want to make array as readonly, you can add `const assertion`. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

2022-07-23 14:12 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  ];
Also, why do you use `sneak_case` for column defenitions?

2022-07-23 16:35 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  public displayedColumns: readonly string[] = [
There is no need in type annotation

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/app.component.css
> +/* stylelint-disable-next-line no-empty-source */
You can delete empty files.

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/app.module.ts
>  import { AppComponent } from './app.component';
Please place imports closely

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.css
> +  width: 90%;
1. You shouldn't define component sizes, because it inconvenient for parent. For example, parent component would want this component to take whole horizontal space, it couldn't be done now.
2. `width: 90%` could look bad on small screens. Prefer using paddings.

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +<table *ngIf="animeList$ | async as animeList" mat-table [dataSource]="animeList" class="table mat-elevation-z8" aria-describedby="Anime Table">
I suggest to place attributes each on new line, if attributes count is more than 3.

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +      <img [src]="anime.image" style="width: 150px;" alt="Anime Image"/>
I suggest to use empty alt text (`alt=""`).

Alt text should explain what's on the image. In best scenario, it would something like "man standing in the forest". But we don't get such information from api. For person that uses screen reader, "Anime Image" isn't meaningful.

2022-07-23 16:37 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +      <img [src]="anime.image" style="width: 150px;" alt="Anime Image"/>
Please don't use inline styles.

2022-07-24 15:27 UTC, maxineo approved these changes

2022-07-25 00:50 UTC, timofei-maximov-saritasa approved these changes

2022-07-25 01:09 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  aria-describedby="Anime Table"
You are using `aria-describedby` in a wrong way. It should [lists the ids of the elements that describe the object](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby#description).

2022-07-25 01:09 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public displayedColumns = [
Add `readonly`

2022-07-25 01:09 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +import { PaginationMapper } from '@js-camp/core/mappers/pagination.mapper';
Don't forget to group imports of the same deep level together

2022-07-25 01:09 UTC, panov-aleksey-saritasa commented on apps/angular/src/theme/styles.css
> +}
Why do you need this?

2022-07-25 01:09 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +
Please, do not write *observer*, *stream* and etc. in docs

2022-07-25 01:36 UTC, dbitkovski requested changes

2022-07-25 01:36 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +  aria-describedby="Anime Table"
Use `trackBy` property to improve performance:
[Angular trackBy](https://angular.io/api/core/TrackByFunction)
[MatTable trackBy](https://angular.io/api/core/TrackByFunction)

2022-07-25 01:36 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +import { AnimeService } from '../../../../../core/services/anime.service';
It will be much convenient to work if you have alias for angular `core` folder also

2022-07-25 01:36 UTC, dbitkovski commented on apps/angular/src/app/features/anime/pages/anime-list-page/anime-list-page.component.ts
> +  public constructor() {}
you can remove empty constructor

2022-07-25 01:36 UTC, dbitkovski commented on apps/angular/src/core/interceptors/api-key-interceptor.ts
> +    req.headers.append('Api-Key', this.appConfigService.apiKey);
I'm might be wrong but angular recommended to clone the request object and not mutate it's state:
https://angular.io/guide/http#setting-default-headers
Sorry if this is outdated info :cat:

2022-07-25 01:36 UTC, dbitkovski commented on apps/angular/src/index.html
> +</head>
Indent issues

2022-07-25 05:46 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +import { AnimeService } from '../../../../../core/services/anime.service';
Discussed on slack, nx eslint rule does not allow it

2022-07-25 05:49 UTC, dmitriqm commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +import { AnimeService } from '../../../../../core/services/anime.service';
the nx rule does not allow alias

2022-07-27 04:06 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-28 03:33 UTC, chernodub commented on apps/angular/src/app/features/anime/anime-routing.module.ts
> +const routes: Routes = [{ path: '', component: AnimeListPageComponent }];
Consider setting a title for the page https://angular.io/guide/router#setting-the-page-title. This will increase the UX of your app

2022-07-28 03:33 UTC, chernodub commented on apps/angular/src/environments/environment.ts
> +  apiUrl: 'https://api.camp-js.saritasa.rocks/api/v1/',
@dmitriqm please always provide a link or a quote in such case. Sometimes people could not have the context that you have.

2022-07-28 03:35 UTC, chernodub commented
@dmitriqm what is the purpose of this PR? I do not see any valuable changes related to `JS19-322-table-paginaiton-sorted`? Should this branch be a base of #1? The base of this PR should be `develop`?

2022-07-28 05:23 UTC, dmitriqm commented on apps/angular/src/theme/styles.css
> +}
Discussed with @panov-aleksey-saritasa in slack

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/project.json
> +          "apps/react/**/*.css"
I'm not sure but it looks like a typo in `lintFilePatterns`. It looks like path to React project is provided in Angular project configuration.

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/app/app.module.ts
> +const httpInterceptorProviders = [
Let's add type for `httpInterceptorProviders`. If I'm not mistaken Angular has `Provider` type.

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-routing.module.ts
> +const routes: Routes = [{ path: '', title: 'Anime list', component: AnimeListPageComponent }];
In my opinion a routing module for small feature is redundant. We can add routes directly to `anime.module.ts`.

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +      {{ (anime.airedStart | date: "MMM yyyy") || "Not started" }}
Usually we have the same date format across our app. So we can move it to constant variable and use it everywhere.

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.animeList$ = animeService.getAnimeList();
If a class member is not a parameter property and may be declared in a single line, we can initialise it where it's declared. Sometimes it helps us drop the constructor entirely. ([wiki](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-short-field-initializers))

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/core/services/anime.service.ts
> +        map(response => response.results),
It seems a bit strange to me that we use a mapper for pagination but don't use the mapped pagination values.
If we need to display the pagination values in UI we can return `Pagination<Anime>` from this method. Inside the component we can use these values as needed (e.g. display `results` in table and `count` inside <mat-pagintaor>).

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/theme/styles.css
> +}
@dmitriqm Please add some context why you consider this 'Resolved'.

2022-07-28 10:55 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  };
Such object seems a bit redundant to me. We can use enum's namespace methods inside template. You just need to assign it to public class member. Something like:
```ts
// anime-table.component.ts
public readonly animeType = AnimeType;
```
```html
<!-- anime-table.component.html -->
<ng-container matColumnDef="type">
  <th mat-header-cell *matHeaderCellDef>Type</th>
  <td mat-cell *matCellDef="let anime">{{ animeType.toReadable(anime.type) }}</td>
</ng-container>
```

2022-07-29 12:56 UTC, dbitkovski approved these changes

2022-07-29 12:56 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly mountYearFormat = monthYearFormat;
Fix typo: *mount*

2022-07-29 12:56 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public constructor(private animeService: AnimeService) {}
We prefer to put class constructor before methods. It's a common practice to order class members make navigation easier because you know what to expect

2022-07-29 12:56 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public constructor(private animeService: AnimeService) {}
And don't forget to add `readonly` modifier. I think it's not supposed to be re-assigned :)

2022-08-01 08:18 UTC, danilkukryakov approved these changes

2022-08-01 08:18 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public trackByAnimeList(_index: number, anime: Anime): Anime['id'] {
Maybe rename to `trackByAnimeId` or `trackById`

2022-08-01 08:18 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/pages/anime-list-page/anime-list-page.component.css
> +  display: block;
I guess we can avoid `display: block` to reduce confusion.
Usually we add `:host { display: block; }` for our Angular components.
So you can add the following code to `anime-table.component.css`:
```css
:host {
  display: block;
}
```
After this change we can remove 'display' in `anime-list-page.component.css`.

In addition, you can add this to Angular schematics for generating components with `display: block` by default. Check [docs](https://next.angular.io/cli/generate#component) (see `--display-block` option) for more information.

2022-08-03 06:08 UTC, merged