Add angular table managment feature #JC19-410
saritasa-nest/camp-js-2022-dmitry-maslov pull request #5
Opened 2022-07-28 19:42 UTC by dmitriqm

2022-07-29 08:27 UTC, kristinaSvobodinaSaritasa requested changes

2022-07-29 08:27 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        [formControl]="filterForms.controls.search"
You can write formControlName = "search",[ example in docs]( https://angular.io/api/forms/FormControlName#register-formcontrol-within-a-group)

2022-07-29 08:27 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        *ngIf="filterParams$ | async as filterParams"
I can't understand why you need this condition, and if !filterParams there is label `Search`,but there isn't input?

2022-07-29 08:27 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    [pageSizeOptions]="[5, 10, 20]"
It is better use constant.

2022-07-29 08:27 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +          const queryLimit = params[QueryParams.Limit];
This code is really hard to read, please try to reduce this by moving some logic in separate methods.

2022-08-01 13:15 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +      map(paginationParams => ({
Why do you not use `getPaginationParamsFromQuery` here?

2022-08-01 13:30 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +        [QUERY_PARAMS_MAP.search]: filterParams.search ?
If I am not mistaken, there is no need to check for undefined, if you send {queryParams: {search:undefined}} it will be correct and there isn't any query params in url. Please check it.

2022-08-01 13:34 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/services/anime.service.ts
> +    }
I think you can also move it to the mapper

2022-08-01 13:37 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/services/anime.service.ts
> +export interface GetPaginatedAnimeListParams {
Strange name for interface, I think word `get` is redundant.

2022-08-08 04:02 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-08 04:02 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +  resultMapper: (resultDto: TDto) => T;
Have you intentionally omitted readonly?

2022-08-08 17:17 UTC, kristinaSvobodinaSaritasa approved these changes

2022-08-09 04:56 UTC, dbitkovski approved these changes

2022-08-09 04:56 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public isLoading$ = new BehaviorSubject<boolean>(true);
I think you can mark these fields with `readonly` as well

2022-08-09 08:54 UTC, merged