Add Angular authorization feature #JC19-430
saritasa-nest/camp-js-2022-dmitry-maslov pull request #6
Opened 2022-08-09 07:51 UTC by dmitriqm

2022-08-11 01:37 UTC, panov-aleksey-saritasa requested changes

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/components/registration-form/registration-form.component.ts
> +  });
```suggestion
    return this.formBuilder.nonNullable.group({
      email: ['', [Validators.required, Validators.email]],
      firstName: ['', [Validators.required]],
      lastName: ['', [Validators.required]],
      password: ['', [Validators.required, Validators.pattern(passwordPattern)]],
      passwordConfirm: ['', [Validators.required, AppValidators.matchControl('password')]],
  });
```
You could do it like this, it's less verbose this way

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/guards/authorized.guard.ts
> +/** Guard prevents a current user from accessing a route in case they are authorized. */
```suggestion
/** Guard prevents a current user from accessing a route in case if they are authorized. */
```

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/interceptors/auth-interceptor.ts
> +   * @param url - Request url.
```suggestion
   * @param url Request url.
```

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/mappers/animeSortParams.mapper.ts
> +   */
Usually sorting mechanism is the same for every entity, there is no need to make it anime specific

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/mappers/mappers.ts
> +  fromDto(data: TDto): TDomain;
Missing readonly, prefer inline docs

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/models/validation-error-code.ts
> +/**
Add readonly, missing inline code
Don't just copypaste code, make it better 🙃

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +/** Params for {getPaginatedAnimeList} method.*/
```suggestion
/** Params for {@link getPaginatedAnimeList} method.*/
```
https://jsdoc.app/tags-inline-link.html

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +  paginationParams: PaginationParams;
Missing readonly?

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +   * Register new user .
```suggestion
   * Register new user.
```

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +   * Refresh user's secret.
I see that sometimes in docs you add `s` at the end of the starting verb and sometimes not. Could you be consistent and stick to one approach?

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/http-backend.service.ts
> +export class HttpBackendClient extends HttpClient {
Why do you need this? I don't see it being used anywhere

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/user.service.ts
> +  // }
Please, remove commented code

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/utils/rxjs/listen-control-touched.ts
> +export function listenControlTouched<T extends AbstractControl>(
Seems unused

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.html
> +      </div>
```suggestion
      <div>
         <a mat-flat-button routerLink="/auth">Login</a>
      </div>
```

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on libs/core/models/registration.ts
> +  readonly avatar?: string;
*Avatar* is not meaningful name by itself, consider changing it to `avatarUrl` or `avatarURL`

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on libs/core/models/user-secret.ts
> +  readonly access: string;
*refresh* and *access* are actually vebs, such naming for object properties could be confusing, don't you think?
```suggestion
  readonly refreshToken: string;

  /** Access token. */
  readonly accessToken: string;
```

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.ts
> +  public isAuthorized$ = this.userService.isAuthorized$;
Don't forget about `readonly` 🙃

2022-08-11 01:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.ts
> +      .subscribe();
Even if you are using `first()`, I still recommend unsubscribing. It could save your app from memory leaks in cases when a stream for some reason could not emit any value

2022-08-11 06:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/components/registration-form/registration-form.component.html
> +  (submit)="handleRegistrationSubmit()"
The same as above about `ngSubmit` and `submit`

2022-08-11 06:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/components/registration-form/registration-form.component.ts
> +    this.registrationForm.value;
```suggestion
    const { 
      email, 
      firstName, 
      lastName, 
      password,
    } = this.registrationForm.value;
```

2022-08-11 06:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/components/registration-form/registration-form.component.ts
> +    private formBuilder: FormBuilder,
Don't forget about `readonly` here too.

2022-08-11 06:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/guards/authorized.guard.ts
> +      map(isAuthorized => (isAuthorized ? this.router.parseUrl('/') : true)),
```suggestion
      map(isAuthorized => isAuthorized ? this.router.parseUrl('/') : true),
```

2022-08-11 06:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/mappers/app-error.mapper.ts
> +  >(mapper: ErrorMapper<TDto, TEntity>): MonoTypeOperatorFunction<T> {
```suggestion
  public catchHttpErrorToAppErrorWithValidationSupport<T, TDto, TEntity extends Record<string, unknown>>(
    mapper: ErrorMapper<TDto, TEntity>
  ): MonoTypeOperatorFunction<T> {
```

2022-08-11 06:44 UTC, dmitriqm commented on apps/angular/src/core/services/http-backend.service.ts
> +export class HttpBackendClient extends HttpClient {
I wanted to use and understand, but in the end I took a different approach. I remove it.

2022-08-12 09:26 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/app.component.html
> +</div>
I think, it is a bit wrong to create `div` only to follow right BEM methodology. And I see these classes are not used in CSS file.
```suggestion
<camp-header></camp-header>
<main>
  <router-outlet></router-outlet>
</main>
```

2022-08-12 09:26 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/components/login-form/login-form.component.html
> +      }}</mat-icon>
```suggestion
      <mat-icon appearance="fill">
        {{ shouldShowPassword ? "visibility_off" : "visibility" }}
      </mat-icon>
```

2022-08-12 09:26 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/components/registration-form/registration-form.component.html
> +  <mat-form-field appearance="fill" class="form__field">
I don't see `form` block around `form__field`. I see only `registration-form` :)

2022-08-12 09:26 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/guards/unauthorized.guard.ts
> +      map(isAuthorized => (isAuthorized ? true : this.router.parseUrl('/'))),
```suggestion
      map(isAuthorized => isAuthorized ? true : this.router.parseUrl('/')),
```

2022-08-12 09:26 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +    )
It's not chaining `post` and `pipe` method for `httpClient`. I suggest not to separate the `httpClient` from calling its method or if you prefer your style, then let's make indents for arguments )
```suggestion
    return this.httpClient.post<UserSecretDto>(
      this.loginUrl.toString(),
      loginMapper.toDto(loginData),
    )
```

2022-08-12 10:09 UTC, viktor-sakhno-saritasa approved these changes

2022-08-29 08:00 UTC, closed without merging