[Angular] Displaying details for a selected anime #JC19-440
saritasa-nest/camp-js-2022-dmitry-maslov pull request #7
Opened 2022-08-10 08:55 UTC by dmitriqm

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.css
> +  width: 300px;
Rather than hardcode `width`/`height`, consider using more flexible and robust approach with `min-height(width)`/`max-height(width)`.
We have the section about it in [wiki](https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size)
Also you could check this article https://ishadeed.com/article/defensive-css/, it contains section about hardcoded sizes, but also has some useful advices about css styling overall

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.html
> +  <div class="details__basic">
I don't see a `details` block anywhere, even if it's a class without any styles, please, don't omit it

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.html
> +        </div>
Don't forget to add [trackBy](https://angular.io/api/core/TrackByFunction)

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.ts
> +  public anime$?: Observable<Anime>;
Usually we do initialization of class properties either in `constructor` or declare them in a single line. That way you wouldn't need using the `?:` operator

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.ts
> +  public animeId!: number;
Please, try to avoid the `!` non-null assertion, it's unsafe and technically incorrect in this case, since every input value is `undefined` before the first `ngOnChanges` hook run.
Usually we define value for input values:
```suggestion
  /** Anime id. */
  @Input()
  public animeId: number | null = null; 
```

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.ts
> +    private youTubePlayerService: MultimediaService,
```suggestion
    private readonly animeService: AnimeService,
    private readonly youTubePlayerService: MultimediaService,
```

2022-08-11 02:33 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    <tr mat-row *matRowDef="let row; columns: displayedColumns" (click)="openDetails(row.id)"></tr>
Use more concrete name here instead of `row`, I suppose in this case it should be `anime`

2022-08-11 06:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.html
> +      <mat-card-content *ngIf="anime.studios[0]">
```suggestion
      <mat-card-content *ngIf="anime.studios.length > 0">
```

2022-08-11 06:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    });
Formatting issue

2022-08-12 02:25 UTC, panov-aleksey-saritasa requested changes

2022-08-12 02:25 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/pages/anime-page/anime-page.component.ts
> +    catchError((err: unknown) => of(err));
Avoid nested pipes whenever it's possible. Sometimes it's needed, but usually it just overcomplicates things
```suggestion
    this.anime$ = route.paramMap.pipe(
      map(paramMap => parseInt(paramMap.get('id') ?? '', 10)),
      switchMap(id => animeService.getAnime(id)),
      catchError((err: unknown) => of(err)),
    )
```

2022-08-12 02:25 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/pages/anime-page/anime-page.component.ts
> +    catchError((err: unknown) => of(err));
What's the purpose behind `catchError` here?

2022-08-12 02:25 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.ts
> +  public anime$: Observable<Anime> | null = null;
It seems strange to me that your card components expects an observable as prop. Why couldn't it operate with plain `Anime` object without any subscription stuff?

2022-08-12 06:54 UTC, viktor-sakhno-saritasa requested changes

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime.module.ts
>  import { MaterialModule } from '@js-camp/angular/shared/material.module';
Please, group one level of imports together. Remove redundant empty lines.

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/components/anime-details/anime-details.component.css
> +  font-size: larger;
I think, it would be better to use relative units than pre-defined font size absolute values. UX will be better, when font-size increases or decreased depending on screen size. What do you think?

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    this.router.navigate([`anime/${id}`]);
```suggestion
    this.router.navigate(['anime', id]);
```

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/pages/anime-page/anime-page.component.ts
> +      .pipe(switchMap(id => animeService.getAnime(id)));
```suggestion
    this.anime$ = route.paramMap.pipe(
      map(paramMap => parseInt(paramMap.get('id') ?? '', 10)),
      switchMap(id => animeService.getAnime(id)),
    );
```

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/utils/trackById.ts
> +export function trackById<T extends Object & { id: number | string; }>(
```suggestion
export function trackById<T extends { id: number | string; }>(
```

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +import { Anime } from '@js-camp/core/models/anime';
The same as above, about one level imports grouping.

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/multimedia.service.ts
> +  public constructor(@Inject(DOCUMENT) private document: Document) {}
Missing readonly?

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/user.service.ts
> +  private returnUrl?: string;
Can we avoid optional type? Just initialize this property with `''` value.

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on libs/core/mappers/anime.mapper.ts
> +        airedFinish: dto.aired.end === null ? null : new Date(dto.aired.end),
```suggestion
        airedStart: dto.aired.start ? new Date(dto.aired.start) : null,
        airedFinish: dto.aired.end ? new Date(dto.aired.end) : null,
```

2022-08-12 06:54 UTC, viktor-sakhno-saritasa commented on libs/core/models/anime.ts
> +  };
I suggest creating a separate model for date range entities. 
For example:
```
interface DateRange {
  readonly start: Date | null;
  readonly end: Date | null;
}
```
Just think, what if you need another model with date range property? It will help to avoid creation couple of models with `finish` and `start` properties.

2022-08-15 09:24 UTC, viktor-sakhno-saritasa approved these changes

2022-08-17 02:54 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-17 02:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/pages/anime-page/anime-page.component.ts
> +      (switchMap(id => animeService.getAnime(id))),
You can omit parentheses around switchMap

2022-08-17 02:54 UTC, artem-sotnichenko-saritasa commented on libs/core/models/studios.ts
> +import { Immerable, OmitImmerable } from './immerable';
Your filename should be in singular form `studio.ts`

2022-08-26 08:05 UTC, chernodub approved these changes

2022-08-29 07:57 UTC, closed without merging