Add React authorization #JC19-460
saritasa-nest/camp-js-2022-dmitry-maslov pull request #8
Opened 2022-08-19 06:00 UTC by dmitriqm

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/components/AppHeader/AppHeader.tsx
> +
We don't handle anything like logout in UI, we handle user actions, let's improve naming here
```suggestion

  const handleLogoutButtonClick = () => {
    dispatch(AuthActions.logoutUser());
  };

```

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/components/AppHeader/AppHeader.tsx
> +        {/* Read more about routing in MUI here: https://mui.com/guides/routing/ */}
Do you need this doc?

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/components/AppHeader/AppHeader.tsx
> +        <div />
Empty `div`

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/components/AppHeader/index.ts
> +export * from './AppHeader';
Are you sure it's a good idea to create such file for every component? I think it would more convient would to keep one `index.ts` file in the `components` folder that would handle all of export stuff, what do you think?

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/AddUserWrapper/AddUserWrapper.tsx
> +interface AddUserWrapperProps {
I my opinion there is no need to name props in such way. Usually we stick to "one file = one component" principle, so usually there could not be issues with name collisions, why duplicate component name and therefore context for a props name? If we need to export props outside of component scope for some reason, name collisions issue is still easy to resolve via export aliases.

Well, right now we don't have any strict guidelines about this in Saritasa frontend team, so you could leave as it is. But, I just want to hear your reasoning, why do you name it like this?

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/AddUserWrapper/AddUserWrapper.tsx
> +  readonly children: ReactJSXElement;
Wrong docs?
But, anyway, `React` provides useful `ReactNode` type, which you can use here.

Also, if you are interested, you could investigate what exactly the `ReactNode` type is. It could be useful knowledge if want to make type of `children` prop stricter.

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +        <>
I think a more common approach, rather than hiding form on loading, disable it instead

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/RegistrationForm/RegistrationForm.tsx
> +          />
Consider creating a reusable component for passwords

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/pages/LoginPage.tsx
> +    {/* <LoginFormNew /> */}
?

2022-08-20 05:35 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/RegistrationForm/form-setting.ts
> +    firstName: Yup.string().required('This field is required'),
Let's move out all this error messages for forms as constants. This way you could keep error message consistent across the whole app and you wouldn't have to do this copypaste stuff

2022-08-20 05:38 UTC, panov-aleksey-saritasa commented
@dmitriqm When I open you app, I see infinite loading. Is it intended?

2022-08-22 08:04 UTC, golovachev-yaroslav approved these changes

2022-08-22 15:10 UTC, panov-aleksey-saritasa approved these changes

2022-08-22 15:10 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +
If am not mistaken, writing return type is not necessary here
```suggestion

  const handleLoginButtonClick = (value: LoginFormValue) => {
    dispatch(AuthActions.loginUser(value));
  };

```

2022-08-22 15:10 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +        }
To improve tsx readability, consider moving out such stuff into constants or functions

2022-08-23 04:34 UTC, pavelzadorin-saritasa approved these changes

2022-08-25 05:41 UTC, chernodub requested changes

2022-08-25 05:41 UTC, chernodub commented on libs/core/dtos/error.dto.ts
> +export interface ErrorDTO<T> {
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#dtos

2022-08-25 05:41 UTC, chernodub commented on libs/core/mappers/app-error.mapper.ts
> +export class AppErrorMapper {
Seems like you never use it?

2022-08-25 05:41 UTC, chernodub commented on libs/core/mappers/mappers.ts
> +export interface IMapperFromDto<TDto, TModel> {
Dead code, never used

2022-08-25 05:41 UTC, chernodub commented on package.json
> +    "formik-mui-x-date-pickers": "^0.0.1",
Is it ever used?

2022-08-29 07:57 UTC, closed without merging